### ISSUE TITLE
About ConvLSTM cell

### ISSUE THREAD

**Issue by faye33** [phongnhhn92/RGBDNet#2]
Your idea of Spatial-temporal consistency is very interesting! But I didn't make it to find how it is implemented in code level (like `encoder-ConvLSTM-decoder`). 
Please I Really need you to advise the certain file >.<
Many thanks!!

**Comment by phongnhhn92** [comment]
Thank @faye33 for your interest in my work! You are right, this is the old version without the STM. I will push the lastest version here soon.

**Comment by faye33** [comment]
Great! Thank you for your prompt reply!

**Comment by faye33** [comment]
Hello there. Looks like the code is still the old version without ConvLSTM, any chance we can see the correct version please?
