### ISSUE TITLE
About dtu_novelViews/test.txt

### ISSUE THREAD

**Issue by Gilgamesh666666** [phongnhhn92/RGBDNet#3]
Hi,

Thank you for the share your excellent work! I want to test the model trained by myself, but I find there does not exist the file `./datasets/lists/dtu_novelViews/test.txt.` Is it actually `./datasets/lists/dtu/test.txt`?

Best regards

**Comment by phongnhhn92** [comment]
@Gilgamesh666666 Hi, you can create your own test.txt based on the example in the dtu folder if you need to test on a specific scene.
